apiVersion: v1
kind: ConfigMap
metadata:
  name: database-test-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-test-api-secrets
type: Opaque
data:
  # Add your base64 encoded connection strings here if needed
  # DefaultConnectionString: <base64-encoded-connection-string>
stringData:
  # Or use stringData for plain text (Kubernetes will encode them)
  # DefaultConnectionString: "Server=tcp:yourserver.database.windows.net,1433;Database=yourdatabase;User ID=yourusername;Password=yourpassword;Encrypt=true;"
