apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-test-api
  labels:
    app: database-test-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-test-api
  template:
    metadata:
      labels:
        app: database-test-api
    spec:
      containers:
        - name: database-test-api
          image: crintegrationappsnoprod01.azurecr.io/database-test-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          # Health Checks
          livenessProbe:
            httpGet:
              path: /api/DatabaseTest/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/DatabaseTest/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          # Resource limits (opcional pero recomendado)
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
