apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ required "MI clientId requerido" .Values.workloadIdentity.clientId | quote }}
automountServiceAccountToken: true